/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/assets/model/bamboo.gltf 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('/bamboo.gltf')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[-26.305, -5, 6.171]} scale={[2.213, 2.126, 2.399]}>
          <group position={[-1.15, 0, 1.571]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.04, 1.201, 1]}>
            <group rotation={[Math.PI / 2, 0, 0]}>
              <group position={[20.805, 0, 0]}>
                <mesh geometry={nodes.Object_15.geometry} material={nodes.Object_15.material} />
                <mesh geometry={nodes.Object_16.geometry} material={nodes.Object_16.material} />
              </group>
              <group position={[16.607, 0, 0]}>
                <mesh geometry={nodes.Object_34.geometry} material={nodes.Object_34.material} />
                <mesh geometry={nodes.Object_35.geometry} material={nodes.Object_35.material} />
                <mesh geometry={nodes.Object_36.geometry} material={nodes.Object_36.material} />
              </group>
              <group position={[18.7, 1.222, 0]} rotation={[0, 0, -0.17]}>
                <mesh geometry={nodes.Object_38.geometry} material={nodes.Object_38.material} />
                <mesh geometry={nodes.Object_39.geometry} material={nodes.Object_39.material} />
                <mesh geometry={nodes.Object_40.geometry} material={nodes.Object_40.material} />
              </group>
              <group position={[15.205, 0.343, -0.185]} rotation={[0, 0, 0.168]} scale={[0.909, 1, 0.97]}>
                <mesh geometry={nodes.Object_66.geometry} material={nodes.Object_66.material} />
                <mesh geometry={nodes.Object_67.geometry} material={nodes.Object_67.material} />
                <mesh geometry={nodes.Object_68.geometry} material={nodes.Object_68.material} />
              </group>
            </group>
          </group>
        </group>
        <directionalLight intensity={0.7} decay={2} rotation={[-0.506, 0.629, 0.756]} target={nodes.Directional_Light.target}>
          <primitive object={nodes.Directional_Light.target} position={[0, 0, -1]} />
        </directionalLight>
        <PerspectiveCamera makeDefault={false} far={100000} near={70} fov={45} position={[82.05, 29.713, -112.523]} rotation={[-2.883, 0.614, 2.991]} />
      </group>
    </group>
  )
}

useGLTF.preload('/bamboo.gltf')
